import { DomainError } from '@/core/shared/domain/errors/DomainError';
import { AppError } from '@/shared/errors/AppError';
import {
  DomainErrorStatusMap,
  mapDomainErrorToAppError,
  rethrowDomainError,
  executeWithDomainErrorMapping,
} from '@/core/shared/application/errors/DomainErrorMapper';

const ERROR_STATUS_MAP: DomainErrorStatusMap = {
  WALLET_ALREADY_EXISTS: 409,
  WALLET_NOT_FOUND: 404,
  WALLET_INVALID_AMOUNT: 400,
  WALLET_INSUFFICIENT_FUNDS: 400,
  WALLET_LOCKED_BALANCE_EXCEEDED: 400,
  WALLET_INSUFFICIENT_LOCKED_FUNDS: 400,
  MONEY_INVALID_AMOUNT: 400,
  MONEY_INVALID_CURRENCY: 400,
  MONEY_CURRENCY_MISMATCH: 400,
  MONEY_NEGATIVE_RESULT: 400,
  MONEY_NEGATIVE_FACTOR: 400,
  CURRENCY_INVALID_CODE: 400,
  MONEY_SECURITY_DEPOSIT_MAX_AMOUNT: 400,
  MONEY_SECURITY_DEPOSIT_DAILY_LIMIT: 429,
  MONEY_SECURITY_DEPOSIT_DAILY_COUNT: 429,
  MONEY_SECURITY_WITHDRAWAL_MAX_AMOUNT: 400,
  MONEY_SECURITY_WITHDRAWAL_DAILY_LIMIT: 429,
  MONEY_SECURITY_WITHDRAWAL_DAILY_COUNT: 429,
  MONEY_SECURITY_WITHDRAWAL_VELOCITY: 429,
  MONEY_SECURITY_PIX_CHANGED_RECENTLY: 403,
  MONEY_SECURITY_PIX_KEY_LINKED: 403,
  MONEY_SECURITY_ACCOUNT_TOO_NEW: 403,
  MONEY_SECURITY_TOO_MANY_FAILED_ATTEMPTS: 429,
  COMPLIANCE_IDENTITY_REQUIRED: 403,
  COMPLIANCE_KYC_NOT_CONFIGURED: 503,
  COMPLIANCE_KYC_REJECTED: 400,
  RESPONSIBLE_GAMBLING_SELF_EXCLUDED: 403,
  RESPONSIBLE_GAMBLING_TIME_OUT_ACTIVE: 403,
  RESPONSIBLE_GAMBLING_DEPOSIT_LIMIT_EXCEEDED: 403,
  RESPONSIBLE_GAMBLING_BET_LIMIT_EXCEEDED: 403,
  RESPONSIBLE_GAMBLING_INVALID_DATE: 400,
};

export const mapWalletDomainError = (error: DomainError): AppError =>
  mapDomainErrorToAppError(error, ERROR_STATUS_MAP);

export const rethrowWalletDomainError = (error: unknown): never =>
  rethrowDomainError(error, ERROR_STATUS_MAP);

export const executeWithWalletErrorMapping = async <T>(operation: () => Promise<T>): Promise<T> =>
  executeWithDomainErrorMapping(operation, ERROR_STATUS_MAP);
